name: Deploy to AWS

on:
  workflow_dispatch:  # Manuel trigger

#  pull_request:
#    types:
#      - closed  # Trigger when PR branch merged to main
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -f ././BasicWebAPI/Dockerfile -t basic_web_api:latest .

      - name: Tag Docker Image
        run: |
          docker tag basic_web_api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/basic_web_api:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/basic_web_api:latest

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop basic_web_api || true
            sudo docker rm basic_web_api || true
            
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/basic_web_api:latest
            
            sudo docker run -d --name basic_web_api -p 8080:8080 -p 8081:8081 ${{ secrets.DOCKER_HUB_USERNAME }}/basic_web_api:latest
