name: Deploy to AWS

on:
  workflow_dispatch:  # Manuel trigger

#  pull_request:
#    types:
#      - closed  # Trigger when PR branch merged to main
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t BasicWebAPI:latest .

      - name: Tag Docker Image
        run: |
          docker tag BasicWebAPI:latest ${{ secrets.DOCKER_HUB_USERNAME }}/BasicWebAPI:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/BasicWebAPI:latest

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop BasicWebAPI || true
            docker rm BasicWebAPI || true
            
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/BasicWebAPI:latest
            
            docker run -d --name BasicWebAPI -p 8080:8080 -p 8081:8081 ${{ secrets.DOCKER_HUB_USERNAME }}/BasicWebAPI:latest
